### ISSUE TITLE
suggestion about showing animation

### ISSUE THREAD

**Issue by zlainsama** [VazkiiModsArchive/Emotes#1]
how about hides model by cancelling net.minecraftforge.client.event.RenderPlayerEvent.Pre and then playing the animation, when you done you can ignore any further events to have them back. so that you can avoid conflicts with mods like galacticraft

**Comment by Vazkii** [comment]
That doesn't make any sense...

**Comment by zlainsama** [comment]
i thought it was a good idea to avoid using hacky asm

**Comment by zlainsama** [comment]
btw, what about other model changing mods like more player models 2?
