### ISSUE TITLE
Cauldron Server wants permission to use emotes

### ISSUE THREAD

**Issue by X00LA** [VazkiiModsArchive/Emotes#2]
Hi,

I installed your mod on a Cauldron server but when anyone, included Admin and Mods, want to use it, they get a message that they don't have permission for.

Is there any way to get this working? Are there any permissions to set for?

Hope you can help me.

Thank's,

X00LA

**Comment by Vazkii** [comment]
## I have done no specific configuration for cauldron, there should be a node there somewhere but I don't know how it assigns them

~V
Wednesday, 17 September 2014, 10:31AM +01:00 from X00LA notifications@github.com:
Hi,
I installed your mod on a Cauldron server but when anyone, included Admin and Mods, want to use it, they get a message that they don't have permission for.
Is there any way to get this working? Are there any permissions to set for?
Hope you can help me.
Thank's,
X00LA
